# Snapshot report for `built-ins/Function/prototype/apply/index.js`

The actual snapshot is saved in `index.js.snap`.

Generated by [AVA](https://avajs.dev).

## built-ins/Function/prototype/apply/15.3.4.3-1-s.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught ReferenceError: "Array" is not defined',
    }

## built-ins/Function/prototype/apply/15.3.4.3-2-s.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught ReferenceError: "Array" is not defined',
    }

## built-ins/Function/prototype/apply/15.3.4.3-3-s.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught ReferenceError: "Array" is not defined',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A12.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught TypeError: cannot convert undefined to object',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A1_T1.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'NotImplementedException: Cannot call `Function` to create new functions at runtime.',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A1_T2.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught Test262Error: Expected SameValue(«undefined», «function») to be true',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A3_T1.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:34:40: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_this->*"field", make_shared<String>("strawberry"), make_shared<String>("The value of this[\\"field\\"] is expected to be \\"strawberry\\"")));␊
                                             ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A3_T10.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:34:40: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_this->*"feat", make_shared<Number>(1), make_shared<String>("The value of this[\\"feat\\"] is expected to be 1")));␊
                                             ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A3_T2.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:34:40: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_this->*"field", make_shared<String>("green"), make_shared<String>("The value of this[\\"field\\"] is expected to be \\"green\\"")));␊
                                             ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A3_T3.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:34:40: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_this->*"field", make_shared<String>("battle"), make_shared<String>("The value of this[\\"field\\"] is expected to be \\"battle\\"")));␊
                                             ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A3_T4.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:34:40: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_this->*"field", make_shared<String>("oil"), make_shared<String>("The value of this[\\"field\\"] is expected to be \\"oil\\"")));␊
                                             ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A3_T5.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:36:40: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_this->*"feat", make_shared<String>("in da haus"), make_shared<String>("The value of this[\\"feat\\"] is expected to be \\"in da haus\\"")));␊
                                             ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A3_T6.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:37:40: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_this->*"feat", make_shared<String>("kamon beyba"), make_shared<String>("The value of this[\\"feat\\"] is expected to be \\"kamon beyba\\"")));␊
                                             ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A3_T7.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:35:40: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_this->*"feat", make_shared<String>("in da haus"), make_shared<String>("The value of this[\\"feat\\"] is expected to be \\"in da haus\\"")));␊
                                             ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A3_T8.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:36:40: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_this->*"feat", make_shared<String>("kamon beyba"), make_shared<String>("The value of this[\\"feat\\"] is expected to be \\"kamon beyba\\"")));␊
                                             ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A3_T9.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:34:40: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_this->*"feat", make_shared<Number>(1), make_shared<String>("The value of this[\\"feat\\"] is expected to be 1")));␊
                                             ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A5_T1.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'NotImplementedException: Cannot call `Function` to create new functions at runtime.',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A5_T2.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'NotImplementedException: Cannot use `Function` as a constructor to create new functions at runtime.',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A5_T3.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:238:19: error: redefinition of '_anonymous_9'␊
      shared_ptr<Value> _anonymous_9 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:233:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_9 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A5_T4.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught TypeError: apply is not a function',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A5_T5.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:238:19: error: redefinition of '_anonymous_9'␊
      shared_ptr<Value> _anonymous_9 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:233:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_9 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A5_T6.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught TypeError: apply is not a function',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A5_T7.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught ReferenceError: "Number" is not defined',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A5_T8.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'NotImplementedException: Cannot call `Function` to create new functions at runtime.',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A7_T1.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No generator defined for ArrayExpression nodes.',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A7_T10.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:37:48: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_typeof(_this->*"shifted"), make_shared<String>("undefined"), make_shared<String>("The value of \`typeof this[\\"shifted\\"]\` is expected to be \\"undefined\\"")));␊
                                                     ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A7_T2.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No generator defined for ArrayExpression nodes.',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A7_T3.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No handler for `UpdateExpression` in `libRazuberiTypeof()` utility',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A7_T4.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No handler for `UpdateExpression` in `libRazuberiTypeof()` utility',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A7_T5.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:36:40: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_this->*"shifted", make_shared<String>("12"), make_shared<String>("The value of this[\\"shifted\\"] is expected to be \\"12\\"")));␊
                                             ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A7_T6.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:37:48: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_typeof(_this->*"shifted"), make_shared<String>("undefined"), make_shared<String>("The value of \`typeof this[\\"shifted\\"]\` is expected to be \\"undefined\\"")));␊
                                                     ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A7_T7.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:35:40: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_this->*"shifted", make_shared<String>("12"), make_shared<String>("The value of this[\\"shifted\\"] is expected to be \\"12\\"")));␊
                                             ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A7_T8.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:35:40: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_this->*"shifted", make_shared<String>("42"), make_shared<String>("The value of this[\\"shifted\\"] is expected to be \\"42\\"")));␊
                                             ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A7_T9.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:36:48: error: use of undeclared identifier '_this'␊
      (scope->*"assert"->*"sameValue").call((_typeof(_this->*"shifted"), make_shared<String>("undefined"), make_shared<String>("The value of \`typeof this[\\"shifted\\"]\` is expected to be \\"undefined\\"")));␊
                                                     ^␊
      1 error generated.`,
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A8_T3.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ✅ Pass |  |

    'No error'

## built-ins/Function/prototype/apply/S15.3.4.3_A8_T4.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'NotImplementedException: Cannot call `Function` to create new functions at runtime.',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A8_T5.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'NotImplementedException: Cannot call `Function` to create new functions at runtime.',
    }

## built-ins/Function/prototype/apply/S15.3.4.3_A8_T6.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'NotImplementedException: Cannot call `Function` to create new functions at runtime.',
    }

## built-ins/Function/prototype/apply/argarray-not-object-realm.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught ReferenceError: "$262" is not defined',
    }

## built-ins/Function/prototype/apply/argarray-not-object.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught Test262Error: Expected a undefined but got a different error constructor with the same name',
    }

## built-ins/Function/prototype/apply/get-index-abrupt.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'ObjectExpression properties of type `ObjectMethod` are not supported at this time',
    }

## built-ins/Function/prototype/apply/get-length-abrupt.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'ObjectExpression properties of type `ObjectMethod` are not supported at this time',
    }

## built-ins/Function/prototype/apply/length.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## built-ins/Function/prototype/apply/name.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## built-ins/Function/prototype/apply/not-a-constructor.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No generator defined for ArrayExpression nodes.',
    }

## built-ins/Function/prototype/apply/this-not-callable-realm.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No generator defined for ArrayExpression nodes.',
    }

## built-ins/Function/prototype/apply/this-not-callable.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No generator defined for ArrayExpression nodes.',
    }
