# Snapshot report for `staging/Temporal/ZonedDateTime/old/index.js`

The actual snapshot is saved in `index.js.snap`.

Generated by [AVA](https://avajs.dev).

## staging/Temporal/ZonedDateTime/old/add.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught ReferenceError: "Temporal" is not defined',
    }

## staging/Temporal/ZonedDateTime/old/compare.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:428:19: error: redefinition of '_anonymous_38'␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:348:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:432:19: error: redefinition of '_anonymous_39'␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:352:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:436:19: error: redefinition of '_anonymous_40'␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:356:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:440:19: error: redefinition of '_anonymous_41'␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:360:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:444:19: error: redefinition of '_anonymous_42'␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:364:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:448:19: error: redefinition of '_anonymous_43'␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:368:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:452:19: error: redefinition of '_anonymous_44'␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:372:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:456:19: error: redefinition of '_anonymous_45'␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:376:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:460:19: error: redefinition of '_anonymous_46'␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:380:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:464:19: error: redefinition of '_anonymous_47'␊
      shared_ptr<Value> _anonymous_47 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:384:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_47 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:468:19: error: redefinition of '_anonymous_48'␊
      shared_ptr<Value> _anonymous_48 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:388:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_48 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:472:19: error: redefinition of '_anonymous_49'␊
      shared_ptr<Value> _anonymous_49 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:392:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_49 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:476:19: error: redefinition of '_anonymous_50'␊
      shared_ptr<Value> _anonymous_50 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:396:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_50 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:480:19: error: redefinition of '_anonymous_51'␊
      shared_ptr<Value> _anonymous_51 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:400:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_51 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:484:19: error: redefinition of '_anonymous_52'␊
      shared_ptr<Value> _anonymous_52 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:404:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_52 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:488:19: error: redefinition of '_anonymous_53'␊
      shared_ptr<Value> _anonymous_53 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:408:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_53 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:492:19: error: redefinition of '_anonymous_54'␊
      shared_ptr<Value> _anonymous_54 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:412:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_54 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:496:19: error: redefinition of '_anonymous_55'␊
      shared_ptr<Value> _anonymous_55 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:416:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_55 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:500:19: error: redefinition of '_anonymous_56'␊
      shared_ptr<Value> _anonymous_56 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:420:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_56 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      fatal error: too many errors emitted, stopping now [-ferror-limit=]␊
      20 errors generated.`,
    }

## staging/Temporal/ZonedDateTime/old/construction-and-properties.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No handler for `ArrayExpression` in `libRazuberiTypeof()` utility',
    }

## staging/Temporal/ZonedDateTime/old/date-time-hours-overflow.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught ReferenceError: "Temporal" is not defined',
    }

## staging/Temporal/ZonedDateTime/old/dst-math.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## staging/Temporal/ZonedDateTime/old/dst-properties.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## staging/Temporal/ZonedDateTime/old/equals.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'BinaryExpressions with operator `*` are not supported at this time',
    }

## staging/Temporal/ZonedDateTime/old/order-of-operations.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:302:19: error: redefinition of '_anonymous_11'␊
      shared_ptr<Value> _anonymous_11 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:285:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_11 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      1 error generated.`,
    }

## staging/Temporal/ZonedDateTime/old/property-bags.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## staging/Temporal/ZonedDateTime/old/reversibility-of-differences.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No generator defined for ArrayExpression nodes.',
    }

## staging/Temporal/ZonedDateTime/old/round.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## staging/Temporal/ZonedDateTime/old/since.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No generator defined for ArrayExpression nodes.',
    }

## staging/Temporal/ZonedDateTime/old/string-parsing.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No generator defined for ArrayExpression nodes.',
    }

## staging/Temporal/ZonedDateTime/old/subtract.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught ReferenceError: "Temporal" is not defined',
    }

## staging/Temporal/ZonedDateTime/old/toInstant.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught ReferenceError: "Temporal" is not defined',
    }

## staging/Temporal/ZonedDateTime/old/toPlainDate.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:355:19: error: redefinition of '_anonymous_28'␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:275:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:359:19: error: redefinition of '_anonymous_29'␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:279:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:363:19: error: redefinition of '_anonymous_30'␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:283:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:367:19: error: redefinition of '_anonymous_31'␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:287:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:371:19: error: redefinition of '_anonymous_32'␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:291:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:375:19: error: redefinition of '_anonymous_33'␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:295:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:379:19: error: redefinition of '_anonymous_34'␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:299:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:383:19: error: redefinition of '_anonymous_35'␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:303:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:387:19: error: redefinition of '_anonymous_36'␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:307:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:391:19: error: redefinition of '_anonymous_37'␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:311:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:395:19: error: redefinition of '_anonymous_38'␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:315:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:399:19: error: redefinition of '_anonymous_39'␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:319:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:403:19: error: redefinition of '_anonymous_40'␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:323:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:407:19: error: redefinition of '_anonymous_41'␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:327:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:411:19: error: redefinition of '_anonymous_42'␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:331:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:415:19: error: redefinition of '_anonymous_43'␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:335:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:419:19: error: redefinition of '_anonymous_44'␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:339:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:423:19: error: redefinition of '_anonymous_45'␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:343:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:427:19: error: redefinition of '_anonymous_46'␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:347:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      fatal error: too many errors emitted, stopping now [-ferror-limit=]␊
      20 errors generated.`,
    }

## staging/Temporal/ZonedDateTime/old/toPlainMonthDay.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:368:19: error: redefinition of '_anonymous_28'␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:275:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:379:19: error: redefinition of '_anonymous_29'␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:286:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:385:19: error: redefinition of '_anonymous_30'␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:292:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:391:19: error: redefinition of '_anonymous_31'␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:298:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:395:19: error: redefinition of '_anonymous_32'␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:302:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:399:19: error: redefinition of '_anonymous_33'␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:306:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:403:19: error: redefinition of '_anonymous_34'␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:310:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:407:19: error: redefinition of '_anonymous_35'␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:314:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:411:19: error: redefinition of '_anonymous_36'␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:318:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:415:19: error: redefinition of '_anonymous_37'␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:322:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:419:19: error: redefinition of '_anonymous_38'␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:326:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:423:19: error: redefinition of '_anonymous_39'␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:330:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:429:19: error: redefinition of '_anonymous_40'␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:336:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:433:19: error: redefinition of '_anonymous_41'␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:340:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:437:19: error: redefinition of '_anonymous_42'␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:344:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:441:19: error: redefinition of '_anonymous_43'␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:348:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:445:19: error: redefinition of '_anonymous_44'␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:352:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:449:19: error: redefinition of '_anonymous_45'␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:356:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:453:19: error: redefinition of '_anonymous_46'␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:360:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      fatal error: too many errors emitted, stopping now [-ferror-limit=]␊
      20 errors generated.`,
    }

## staging/Temporal/ZonedDateTime/old/toPlainTime.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught ReferenceError: "Temporal" is not defined',
    }

## staging/Temporal/ZonedDateTime/old/toPlainYearMonth.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:368:19: error: redefinition of '_anonymous_28'␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:275:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:379:19: error: redefinition of '_anonymous_29'␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:286:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:385:19: error: redefinition of '_anonymous_30'␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:292:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:391:19: error: redefinition of '_anonymous_31'␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:298:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:395:19: error: redefinition of '_anonymous_32'␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:302:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:399:19: error: redefinition of '_anonymous_33'␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:306:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:403:19: error: redefinition of '_anonymous_34'␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:310:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:407:19: error: redefinition of '_anonymous_35'␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:314:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:411:19: error: redefinition of '_anonymous_36'␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:318:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:415:19: error: redefinition of '_anonymous_37'␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:322:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:419:19: error: redefinition of '_anonymous_38'␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:326:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:423:19: error: redefinition of '_anonymous_39'␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:330:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:427:19: error: redefinition of '_anonymous_40'␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:334:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:433:19: error: redefinition of '_anonymous_41'␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:340:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:437:19: error: redefinition of '_anonymous_42'␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:344:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:441:19: error: redefinition of '_anonymous_43'␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:348:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:445:19: error: redefinition of '_anonymous_44'␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:352:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:449:19: error: redefinition of '_anonymous_45'␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:356:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:453:19: error: redefinition of '_anonymous_46'␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:360:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      fatal error: too many errors emitted, stopping now [-ferror-limit=]␊
      20 errors generated.`,
    }

## staging/Temporal/ZonedDateTime/old/toString.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## staging/Temporal/ZonedDateTime/old/until.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'No generator defined for ArrayExpression nodes.',
    }

## staging/Temporal/ZonedDateTime/old/with.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## staging/Temporal/ZonedDateTime/old/withCalendar.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:357:19: error: redefinition of '_anonymous_28'␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:277:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:361:19: error: redefinition of '_anonymous_29'␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:281:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:365:19: error: redefinition of '_anonymous_30'␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:285:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:369:19: error: redefinition of '_anonymous_31'␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:289:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:373:19: error: redefinition of '_anonymous_32'␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:293:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:377:19: error: redefinition of '_anonymous_33'␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:297:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:381:19: error: redefinition of '_anonymous_34'␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:301:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:385:19: error: redefinition of '_anonymous_35'␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:305:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:389:19: error: redefinition of '_anonymous_36'␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:309:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:393:19: error: redefinition of '_anonymous_37'␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:313:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:397:19: error: redefinition of '_anonymous_38'␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:317:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:401:19: error: redefinition of '_anonymous_39'␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:321:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:405:19: error: redefinition of '_anonymous_40'␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:325:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:409:19: error: redefinition of '_anonymous_41'␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:329:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:413:19: error: redefinition of '_anonymous_42'␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:333:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:417:19: error: redefinition of '_anonymous_43'␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:337:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:421:19: error: redefinition of '_anonymous_44'␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:341:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:425:19: error: redefinition of '_anonymous_45'␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:345:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:429:19: error: redefinition of '_anonymous_46'␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:349:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      fatal error: too many errors emitted, stopping now [-ferror-limit=]␊
      20 errors generated.`,
    }

## staging/Temporal/ZonedDateTime/old/withPlainDate.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ❌ Fail | An error occurred while transpiling the test with `@razuberi/transpiler`. |
> | Compile | ⬜ Skip | *This stage did not run.* |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: 'We don\'t know what to do with this node type. We were previously a Statement but we can\'t fit in here?',
    }

## staging/Temporal/ZonedDateTime/old/withPlainTime.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ✅ Pass |  |
> | Execute | ❌ Fail | An error occurred while executing the test program. |

    Error {
      message: 'Uncaught ReferenceError: "Temporal" is not defined',
    }

## staging/Temporal/ZonedDateTime/old/withTimezone.js

> | Test Stage | Status | Details |
> | :-- | :-- | :-- |
> | Load | ✅ Pass |  |
> | Transpile | ✅ Pass |  |
> | Compile | ❌ Fail | An error occurred while compiling the test with `g++`. |
> | Execute | ⬜ Skip | *This stage did not run.* |

    Error {
      message: `<stdin>:355:19: error: redefinition of '_anonymous_28'␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:275:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_28 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:359:19: error: redefinition of '_anonymous_29'␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:279:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_29 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:363:19: error: redefinition of '_anonymous_30'␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:283:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_30 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:367:19: error: redefinition of '_anonymous_31'␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:287:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_31 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:371:19: error: redefinition of '_anonymous_32'␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:291:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_32 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:375:19: error: redefinition of '_anonymous_33'␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:295:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_33 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:379:19: error: redefinition of '_anonymous_34'␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:299:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_34 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:383:19: error: redefinition of '_anonymous_35'␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:303:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_35 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:387:19: error: redefinition of '_anonymous_36'␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:307:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_36 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:391:19: error: redefinition of '_anonymous_37'␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:311:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_37 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:395:19: error: redefinition of '_anonymous_38'␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:315:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_38 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:399:19: error: redefinition of '_anonymous_39'␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:319:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_39 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:403:19: error: redefinition of '_anonymous_40'␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:323:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_40 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:407:19: error: redefinition of '_anonymous_41'␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:327:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_41 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:411:19: error: redefinition of '_anonymous_42'␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:331:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_42 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:415:19: error: redefinition of '_anonymous_43'␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:335:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_43 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:419:19: error: redefinition of '_anonymous_44'␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:339:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_44 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:423:19: error: redefinition of '_anonymous_45'␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:343:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_45 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:427:19: error: redefinition of '_anonymous_46'␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      <stdin>:347:19: note: previous definition is here␊
      shared_ptr<Value> _anonymous_46 (shared_ptr<Scope> scope, shared_ptr<Value> _this, vector<shared_ptr<Value> > arguments) {␊
                        ^␊
      fatal error: too many errors emitted, stopping now [-ferror-limit=]␊
      20 errors generated.`,
    }
